# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'usertestapp' do
  pod 'PureLayout', git: 'https://github.com/PureLayout/PureLayout'
  pod 'PromiseKit'
  pod 'SwiftyJSON', '~> 2.3.0'
  pod 'Alamofire', '~> 3.0'
end

target 'usertestappTests' do

end

target 'usertestappUITests' do

end
