# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'usertestapp' do

end

target 'usertestappTests' do

end

target 'usertestappUITests' do

end

